### ISSUE TITLE
Support Amazon Bedrock as inference provider

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#122]
**Description**
Add Amazon Bedrock as a supported inference provider

**Tasks**
- [ ] Implement abstraction for Amazon Bedrock
- [ ] Add example under [provider folder](https://github.com/i-am-bee/bee-agent-framework/tree/main/examples/llms/providers)
- [ ] Update [docs](https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/llms.md) to include supported interfaces
- [ ] Run tests

**Additional context**
3x requests from LI
See [comment](https://www.linkedin.com/feed/update/urn:li:activity:7254808957368573952?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7254808957368573952%2C7254814681716928513%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287254814681716928513%2Curn%3Ali%3Aactivity%3A7254808957368573952%29)

**Comment by Tomas2D** [comment]
Relevant documentation page: https://i-am-bee.github.io/bee-agent-framework/#/llms?id=adding-a-new-provider-adapter

**Comment by abughali** [comment]
@mmurad2 please assign it to me

**Comment by Tomas2D** [comment]
Any progress @abughali?

**Comment by Tomas2D** [comment]
Temporary workaround with the use of LangChain. @MartinRistov 

```typescript
import { BaseMessage } from "bee-agent-framework/llms/primitives/message";
import { LangChainChatLLM } from "bee-agent-framework/adapters/langchain/llms/chat";

// you need to install this package first @langchain/community
import { BedrockChat } from "@langchain/community/chat_models/bedrock";

console.info("===CHAT===");
const llm = new LangChainChatLLM(
    new Bedrock({
      model: "anthropic.claude-v2",
      region: process.env.BEDROCK_AWS_REGION ?? "us-east-1",
      // endpointUrl: "custom.amazonaws.com",
      credentials: {
        accessKeyId: process.env.BEDROCK_AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY,
      },
      temperature: 0,
      maxTokens: undefined,
      maxRetries: 2,
      // other params...
    })
);

const response = await llm.generate([
  BaseMessage.of({
    role: "user",
    text: "Hello world!",
  }),
]);
```

Related code: https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/llms/providers/langchain.ts
LangChain documentation: https://js.langchain.com/docs/integrations/llms/bedrock#instantiation
