### ISSUE TITLE
Support Azure OpenAI as inference provider

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#140]
**Description**
Add Azure OpenAI as a supported inference provider

**Tasks**
- [ ]  Implement inference provider[ following these instructions](https://i-am-bee.github.io/bee-agent-framework/#/llms?id=adding-a-new-provider-adapter)
- [ ]  Add example under [provider folder](https://github.com/i-am-bee/bee-agent-framework/tree/main/examples/llms/providers)
- [ ]  Update [docs](https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/llms.md) to include supported interfaces
- [ ]  Run tests

**Comment by Tomas2D** [comment]
Tutorial on how to do so: https://i-am-bee.github.io/bee-agent-framework/#/llms?id=adding-a-new-provider-adapter

**Comment by akihikokuroda** [comment]
Hi!  I hope I can finish #141 soon.  May I try this next?  Or is there something I can enjoy next?

**Comment by mmurad2** [comment]
That's awesome @akihikokuroda - just assigned to you!

**Comment by akihikokuroda** [comment]
I was thinking to use `Generic` to avoid code duplication between AzureOpenAI and OpenAI.  I saw this note in the OpenAI node module [docs](https://www.npmjs.com/package/openai).  It seems that we may need separate code them.

>Microsoft Azure OpenAI
To use this library with [Azure OpenAI](https://learn.microsoft.com/azure/ai-services/openai/overview), use the AzureOpenAI class instead of the OpenAI class.

>[!IMPORTANT] The Azure API shape slightly differs from the core API shape which means that the static types for responses / params won't always be correct.

Is it OK to have very similar separated code for for these adapters?

**Comment by Tomas2D** [comment]
They should be compatible. I would try it if it does not work. You can introduce a separate class.

> Microsoft's Azure team maintains libraries that are compatible with both the OpenAI API and Azure OpenAI services. Read the library documentation below to learn how you can use them with the OpenAI API.

Source: https://platform.openai.com/docs/libraries#azure-openai-libraries
