### ISSUE TITLE
Support GCP Vertex AI as inference provider

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#141]
**Description**
Add GCP Vertex AI as a supported inference provider

**Tasks**

- [ ]  Implement inference provider[ following these instructions](https://i-am-bee.github.io/bee-agent-framework/#/llms?id=adding-a-new-provider-adapter)
- [ ]  Add example under [provider folder](https://github.com/i-am-bee/bee-agent-framework/tree/main/examples/llms/providers)
- [ ]  Update [docs](https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/llms.md) to include supported interfaces
- [ ]  Run tests

**Comment by Tomas2D** [comment]
Tutorial on how to do so: https://i-am-bee.github.io/bee-agent-framework/#/llms?id=adding-a-new-provider-adapter

**Comment by akihikokuroda** [comment]
HI!  I would like try this.  Would you assign to me?  Thanks!

**Comment by mmurad2** [comment]
Awesome! just assigned you @akihikokuroda

**Comment by akihikokuroda** [comment]
Thanks!

**Comment by akihikokuroda** [comment]
I need some guidance here.  

I'm trying to serialize **VertexAI** class from "@google-cloud/vertexai". This class has a member type of **GoogleAuth** from "google-auth-library" class.  I can register both classes to the serializer.  So these are OK.
The issue is that the **VertexAI** has another member type of **VertexAIPreview** that is a class defined in the same package as **VertexAI** class but it is not exposed so I can not register it to the serializer.

How can I workaround this?  
Thanks!

Here is the class definitions : https://github.com/googleapis/nodejs-vertexai/blob/31de0e92bb7e0efd5afca2728d6175095175be04/src/vertex_ai.ts#L43
```
export class VertexAI {
  public readonly preview: VertexAIPreview;
  private readonly project: string;
  private readonly location: string;
  private readonly googleAuth: GoogleAuth;
  private readonly apiEndpoint?: string;
 ......
}

class VertexAIPreview {
  private readonly project: string;
  private readonly location: string;
  private readonly googleAuth: GoogleAuth;
  private readonly apiEndpoint?: string;

  private readonly apiClient: Resources.ApiClient;
  readonly cachedContents: Resources.CachedContents;
.....
}
```

**Comment by Tomas2D** [comment]
Released in v0.0.43

**Comment by mmurad2** [comment]
@akihikokuroda thanks for the contribution!  could you also complete the following so that our docs and examples folders follow suite:
- [ ] Add example under [provider folder](https://github.com/i-am-bee/bee-agent-framework/tree/main/examples/llms/providers)
- [ ]  Update [docs](https://github.com/i-am-bee/bee-agent-framework/blob/main/docs/llms.md) to include supported interfaces

**Comment by Tomas2D** [comment]
I added examples because I wanted to try it with my GCP credentials.

However, the implementation is flawed and needs the following updates.
- `parameters` are not used and are not typed, ideally they should correspond or map to `BaseModelParams. 
-  hence you should completely rework the utility function `createModel`
- you code contains expressions like `for await (const chunk of await response.stream) {`, rewrite to just `for await (const chunk of response.stream) {`
-
