### ISSUE TITLE
Investigate changing default Bee to meta-llama/Llama-3.2-90B-Vision (large) and meta-llama/Llama-3.2-11B-Vision (large)

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#179]
**Description**
Even though llama-3.2 is a multimodal model, we should expect significant improvements in the text domain as well.
Scope of this addition should be limited to text modality, the meta docs say llama-3.2 should be a drop-in replacement for llama-3.1

**Tasks**

- [ ] Test the performance of  meta-llama/Llama-3.2-90B-Vision  and meta-llama/Llama-3.2-11B-Vision  with Bee Agent (and compare to existing llama 3.1 large and small) - without changing system prompt (drop-in replacement only)
- [ ] Investigate if additional prompt optimization is required
- [ ] If we achieve a performance lift, change readme, docs, and OOTB examples to llama-3.2

**Comment by Tomas2D** [comment]
Note that Meta has disallowed access to this model in the EU (both models).

**Comment by Tomas2D** [comment]
However, the model works fine without further ado.

**Comment by mmurad2** [comment]
@Tomas2D updated scope

**Comment by Tomas2D** [comment]
I set llama3.3 as a default for Groq because they have deprecated llama3.1
