### ISSUE TITLE
Create GitHub documentation page to visualize existing markdown docs

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-agent-framework#74]
**Is your feature request related to a problem? Please describe.**
Improve documentation accessibility.

**Describe the solution you'd like**
A dedicated Github documentation page that will serve as a centralized hub to visualize and navigate through the[ existing markdown documentation files](https://github.com/i-am-bee/bee-agent-framework/tree/main/docs).

**Tasks**
- [ ] Investigate and select a documentation framework/tool, ideally one that works with [GitHub Pages](https://pages.github.com).
- [ ] Set up the chosen tool in the repository.
- [ ] Configure the documentation tool to generate pages from the existing markdown files.
- [ ] Test the documentation page to ensure that it is user-friendly and correctly displays the markdown content.
- [ ] Set up CI to automatically deploy updates to the documentation site.
- [ ] Write basic guidelines for future contributions to the documentation.

**Comment by eduardconstantin** [comment]
Hello! I found this: https://docsify.js.org

**Comment by eduardconstantin** [comment]
Yes, I would like to work on this. 
The tool I found deploys the markdown files to GitHub pages. It only needs an index.html to render content form those files.

**Comment by matoushavlena** [comment]
These were some historic considerations for a standalone doc site (not in any order of preference):
https://www.mkdocs.org/
https://docs.readme.com/main/docs/rdme
https://www.markdownguide.org/
https://markdoc.dev/
https://mintlify.com/
https://scalar.com/

@Tomas2D what's your thought? It would be good to understand if docsify is a short term solution or long term one.

**Comment by eduardconstantin** [comment]
I also found docusaurus, docz, gitbook

**Comment by eduardconstantin** [comment]
> `docsify` is a long-hanging fruit; it is easy to set up and modify and an active project with many plugins.
> 
> @eduardconstantin, feel free to start

the best choice in the history of choices
